### PR TITLE
Delete js source files before your coffeefy to prevent errors fixes #302

### LINKED ISSUE #302: lineman new --skip-examples has two fs errors
Tries to delete hello_spec.coffee when it doesn't exist.

### PR DESCRIPTION
**Pull request by mbutsko**
Rather than try to delete them after they were possibly converted, just remove them earlier.

### CODE REVIEW

**Comment by searls** [comment]
Thanks for digging this up!

**Comment by searls** [comment]
fixes #302

**Comment by searls** [comment]
Hey @mbutsko were you able to replicate #302 before you sent this patch? I just tried `lineman new test1234 --skip-examples --coffee` with and without the patch and both exited cleanly.

**Comment by mbutsko** [comment]
So yesterday, I encountered it _without_ the coffee flag:
```
~ % lineman new bob --skip-examples
...

fs.js:77
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
            ^
Error: ENOENT, unlink '/Users/butsko/bob/app/js/hello.coffee'
    at Error (native)
```
Without the flag it shouldn't work without the patch, since it won't turn the .js into .coffee before trying to remove the .coffee. 

Also, I think because it's asynchronously renaming files while at the same time trying to remove them, I can imagine it being intermittent _with the flag_ (it managed to rename both files before attempting to remove them, which would result it no error...?)

**Comment by searls** [comment]
Ah, and perhaps there's something here we can make synchronous.

**Comment by searls** [comment]
Thanks for the explanation

**Pull request merged**
